### ISSUE TITLE
How do you prepare the embedding file?

### ISSUE THREAD

**Issue by Flitternie** [jimth001/Bi-Seq2Seq#3]
Hi!
I recently read the paper of bi-seq2seq and noticed your impressive works. When reproducing the paper work and using your codes, I am confused by the embedding file mentioned in your code.
The dataset I asked from Mark Wu does not contain such embedding file. I noticed that you used fasttext as embedding. 
May I know how you generate the embedding file? Or if possible, would you mind sharing your original preprocessed dataset for me?
Really appreciate your good works! Looking forward to your response.

Regards,
Flitter

**Comment by jimth001** [comment]
Hi Flitter,

Sorry, I have not reserved the embedding file and preprocessed dataset. 
We used the training set you have got to train the word embedding. And we used fasttext with 300 dimensions. Other parameters are set to default.
Hope this will help you!

Yunli
